### ISSUE TITLE
error consol

### ISSUE THREAD

**Issue by NewHopeGame** [ESX-Org/esx_society#13]
error running system event handling function for resource esx_society: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:39: attempt to index a nil value (field '?') stack traceback: server/main.lua:39: in upvalue 'handler' citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162> stack traceback: [C]: in function 'error' citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow' citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131> hitch warning: frame time of 463 milliseconds

**Comment by RomainLanz** [comment]
Hey @NewHopeGame! 👋 

1. What do you do to get this error?
2. Does all of your ESX resource up to date?

**Comment by funzik** [comment]
i have this error, but i have all ressources EX up to date !

[      7859] Error running system event handling function for resource esx_society: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:39: attempt to index a nil value (field '?')
[      7875] stack traceback:
[      7890] 	server/main.lua:39: in upvalue 'handler'
[      7906] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[      7921] stack traceback:
[      7921] 	[C]: in function 'error'
[      7937] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[      7937] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>

**Comment by jiynn** [comment]
`Failed to load script @es_extended/locale.lua.
Error loading script locales/de.lua in resource esx_society: locales/de.lua:7: a                                                                                                                               ttempt to index a nil value (global 'Locales')
stack traceback:
        locales/de.lua:7: in main chunk
Failed to load script locales/de.lua.
Error loading script locales/br.lua in resource esx_society: locales/br.lua:28:                                                                                                                                attempt to index a nil value (global 'Locales')
stack traceback:
        locales/br.lua:28: in main chunk
Failed to load script locales/br.lua.
Error loading script locales/en.lua in resource esx_society: locales/en.lua:35:                                                                                                                                attempt to index a nil value (global 'Locales')
stack traceback:
        locales/en.lua:35: in main chunk
Failed to load script locales/en.lua.
Error loading script locales/fr.lua in resource esx_society: locales/fr.lua:35:                                                                                                                                attempt to index a nil value (global 'Locales')
stack traceback:
        locales/fr.lua:35: in main chunk
Failed to load script locales/fr.lua.
Error loading script server/main.lua in resource esx_society: server/main.lua:18                                                                                                                               6: attempt to index a nil value (global 'ESX')
stack traceback:
        server/main.lua:186: in main chunk
Failed to load script server/main.lua.
`

I am getting these errors during server startup, not sure where to start on the fix...

**Comment by ddh3** [comment]
This isn't an issue with the resource, its user error. If you need help, join discord.

**Comment by Hoften** [comment]
Im getting this. i didnt do anything and then this pops up... 
[    179125] Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:351: server/main.lua:80: attempt to index a nil value (field '?')
[    179140] stack traceback:
[    179140] 	server/main.lua:80: in upvalue 'ref'
[    179140] 	citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
[    179140] 	[C]: in function 'xpcall'
[    179156] 	citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
[    179156] stack traceback:
[    179156] 	[C]: in function 'error'
[    179171] 	citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>
[    180015] [ERROR] [MySQL] Check the error above, an error happens when executing the callback from the query : "SELECT * FROM `user_inventory` WHERE `identifier` = @identifier {@identifier=steam:11000010c1bdf70}"
[    188421] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[    188437] stack traceback:
[    188437] 	server/main.lua:71: in upvalue 'handler'
[    188437] 	citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
[    188453] stack traceback:
[    188453] 	[C]: in function 'error'
[    188453] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[    188468] 	citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>
[    194187] Sending heartbeat to live-internal.fivem.net:30110
[    374203] Sending heartbeat to live-internal.fivem.net:30110
[    554219] Sending heartbeat to live-internal.fivem.net:30110
[    606625] [SAVED] All players
[    734281] Sending heartbeat to live-internal.fivem.net:30110
